services:
  - type: web
    name: cifar10-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: MODEL_PATH
        value: cnn_model_cifar10.h5
      - key: FRONTEND_URL
        value: https://ton-frontend.vercel.app
  